"use client";

import { CalendarDays, ChevronDown } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { StatusBadge } from "@/components/bookings/status-badge";
import { bookingFilters, formatBookingDate, type BookingStatus, type CompanyBooking } from "@/lib/bookings";
import { formatRate, initials } from "@/lib/creator-profile";
import { cn } from "@/lib/utils";

export function CompanyRequestList({ bookings, loadError }: { bookings: CompanyBooking[]; loadError?: string }) {
  const [filter, setFilter] = useState<"all" | BookingStatus>("all");
  const visible = useMemo(() => filter === "all" ? bookings : bookings.filter((booking) => booking.booking_status === filter), [bookings, filter]);
  if (loadError) return <Empty title="Requests couldn't be loaded" description="Refresh the page to try again." />;
  return <><div className="flex gap-2 overflow-x-auto pb-2">{bookingFilters.map((item) => { const count = item.value === "all" ? bookings.length : bookings.filter((booking) => booking.booking_status === item.value).length; return <button key={item.value} onClick={() => setFilter(item.value)} className={cn("shrink-0 rounded-full border px-4 py-2 text-sm font-semibold", filter === item.value ? "border-primary bg-primary text-primary-foreground" : "border-border bg-surface hover:border-primary/40")}>{item.label} <span className="ml-1 opacity-70">{count}</span></button>; })}</div>{visible.length ? <div className="mt-6 space-y-4">{visible.map((booking) => <article key={booking.booking_id} className="rounded-3xl border border-border bg-surface p-5 card-shadow sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-accent text-sm font-extrabold text-primary">{booking.creator_avatar_url ? <Image unoptimized width={48} height={48} src={booking.creator_avatar_url} alt="" className="h-full w-full object-cover" /> : initials(booking.creator_name)}</div><div><div className="flex flex-wrap items-center gap-2"><StatusBadge status={booking.booking_status} /><span className="text-xs text-muted">Sent {new Date(booking.created_at).toLocaleDateString("en", { day: "numeric", month: "short" })}</span></div><h2 className="display mt-2 text-xl font-extrabold">{booking.campaign_title}</h2><Link href={`/creators/${booking.creator_workspace_id}`} className="mt-1 inline-block text-sm font-semibold text-primary hover:underline">{booking.creator_name}</Link><p className="text-xs text-muted">{booking.creator_headline}</p></div></div><div className="pl-16 sm:pl-0 sm:text-right"><p className="text-lg font-extrabold text-primary">{formatRate(booking.price_cents)}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted sm:justify-end"><CalendarDays size={14} />{formatBookingDate(booking.desired_publish_date)}</p></div></div><details className="group mt-5 border-t border-border pt-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-bold">View request details <ChevronDown size={17} className="transition group-open:rotate-180" /></summary><div className="mt-5 grid gap-5 text-sm leading-6 sm:grid-cols-2"><Detail label="Objective" value={booking.campaign_objective} /><Detail label="Requested deliverable" value={booking.deliverable_description} />{booking.company_notes && <Detail label="Your notes" value={booking.company_notes} />}</div></details></article>)}</div> : <Empty title={bookings.length ? "No requests in this view" : "No requests sent yet"} description={bookings.length ? "Choose another status to see your requests." : "Discover a creator and send a campaign brief to start collaborating."} />}</>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 whitespace-pre-line">{value}</p></div>; }
function Empty({ title, description }: { title: string; description: string }) { return <div className="mt-6 flex min-h-64 flex-col items-center justify-center rounded-3xl border border-dashed border-border bg-surface px-6 text-center"><h2 className="display text-2xl font-extrabold">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-muted">{description}</p></div>; }
